### ISSUE TITLE
TODO/editing

### ISSUE THREAD

**Issue by KonstantAnxiety** [KonstantAnxietyTeam/python_project_192#6]
- [x] Проверка ввода на тип данных

- [x] Запрет на ввод существующего кода / программный расчет уникального кода

- [ ] Предупреждение об отсутствии записи с введенным кодом-ссылкой
